### ISSUE TITLE
Banker can name participants

### ISSUE THREAD

**Issue by romaine1989** [ThisIsForTeck/pardna-app#13]
# Technical Context
As a Pardna Banker I want to Give a custom name to participants in a Pardna, so that I can identify who they are

# Objective
Banker user can give a participant a custom name upon creation

# Acceptance Criteria
- User with the correct role (banker) can create a custom name for a participant they add to a Pardna
- If user doesn't have the correct role they won't be able to create a custom name for a participant

**Comment by ezeikel** [comment]
@romaine1989 Wont this just be the name the user set when they signed up. Why would a banker need to name them?
