### ISSUE TITLE
Banker can edit participants name

### ISSUE THREAD

**Issue by romaine1989** [ThisIsForTeck/pardna-app#14]
# Technical Context
As a Pardna Banker I want to Be able to save and amend a participants name, So that I can make a mistake and rectify it in such case

# Objective 
A Banker user can edit the saved name of a participant

# Acceptance Criteria
- User logged in and with Banker role can edit the name of a participant.
- If user is not logged in and does not have the Banker role, they will not be able to edit the name of a participant

**Comment by ezeikel** [comment]
@romaine1989 Same as previous comment. Participants name should come from their info when they signed up to app
