### ISSUE TITLE
Banker can view participant Settlement

### ISSUE THREAD

**Issue by romaine1989** [ThisIsForTeck/pardna-app#19]
# Technical Context
As a Pardna Banker, I want To review when participants have paid in relation to throwing occurrence dates, So that I can identify any hindrances to the Pardna system

# Objective
Banker can navigate to a participant in a Pardna and view the saved dates which reflect when participants have settled their throwing occurrence 

# Acceptance Criteria
- User with the correct role (banker) must be logged in and within a Pardna in order to view the saved settlement dates
- If the user is not logged in, a banker and inside a Pardna, then they will not be able to see this.

**Comment by ezeikel** [comment]
@romaine1989 Covered by #15
