### ISSUE TITLE
Banker can navigate to a specific week

### ISSUE THREAD

**Issue by romaine1989** [ThisIsForTeck/pardna-app#20]
# Technical Context
As a Pardna Banker I want to navigate to a specific week in a Pardna to see participant  settlements, against the outlined throwing occurrence for the Pardna.

So that I can have visibility of how promptly or not participants were to settle their hand in a chosen week of the Pardna

# Objective
Banker can navigate to a specific week within a Pardna and view the saved dates which reflect when participants have settled their throwing occurrence in relation to the Pardna throwing occurrence date set

**Comment by ezeikel** [comment]
@romaine1989 Covered by #15. Maybe add more detail to that ticket if you feel like this is extra

**Comment by romaine1989** [comment]
This is visibility of settlements by way of week. #15 is user specific.
