### ISSUE TITLE
Use can become a Banker/Participant

### ISSUE THREAD

**Issue by romaine1989** [ThisIsForTeck/pardna-app#21]
# Technical Context
As a User, I want to be able to distinguish the type of user I am so that I can either create Parnda's to manage as a Banker. Or join Pardna's to be a part of as a Participant.  

# Objective
A User can select the type user they are in order to conduct or join Pardna's

# Acceptance Criteria
- User will need to register to the app in order to specify the type of user they are. 
- If user is not registered they will be unable to specify the type of user they are

**Comment by ezeikel** [comment]
For now everyone is of `Banker` role - so closing this.
