### ISSUE TITLE
User can log out

### ISSUE THREAD

**Issue by romaine1989** [ThisIsForTeck/pardna-app#25]
# Technical Context
As a User, I want to be able to log out of of the App so that I can stop any accountable activity on the app. 

# Objective
A User can log out of the app in order to not incur any accountable activity on the.

# Acceptance Criteria
- User will need to be registered and logged into the app in order to have the option to log out of the app
- If user is not registered and logged in, they will not be able log out of the app

**Comment by ezeikel** [comment]
All registration tickets can be in one.
