### ISSUE TITLE
Banker can define hand amount

### ISSUE THREAD

**Issue by romaine1989** [ThisIsForTeck/pardna-app#8]
# Technical Context
As a Banker, I want to be able to set the sum of an individual hand (max £50) so that I know how much to collect from each participant.
 

# Acceptance Criteria
- User with the correct role (banker) can set the individual hand
- If user doesn't have the correct role they can't set the individual hand

**Comment by ezeikel** [comment]
@romaine1989 Does hand amount impact duration?
